plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/mnt/d/Projects/auraconnectai/site"
publishOrigin = "config"
commandOrigin = "config"
command = "mkdocs build"

[build.environment]
PYTHON_VERSION = "3.11"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]