site_name: AuraConnect Documentation
site_description: Comprehensive restaurant management platform documentation
site_author: AuraTechWave
site_url: https://docs.auraconnect.com
repo_url: https://github.com/AuraTechWave/auraconnectai
repo_name: auraconnectai
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.prune
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: 
    - Welcome: index.md
    - Quick Start: guides/getting-started.md
    - What's New: CHANGELOG.md
    
  - Getting Started:
    - guides/getting-started.md
    - Installation:
      - Docker Setup: guides/docker-setup.md
      - Local Development: guides/local-setup.md
      - Configuration: guides/configuration.md
    - First Steps:
      - Create Restaurant: guides/first-restaurant.md
      - Add Menu Items: guides/first-menu.md
      - Process Orders: guides/first-order.md
      
  - Core Modules:
    - modules/README.md
    - Restaurant Operations:
      - Orders: modules/orders/README.md
      - Menu: modules/menu/README.md
      - Inventory: modules/inventory/README.md
      - POS Integration: modules/pos/README.md
    - Staff & Finance:
      - Staff Management: modules/staff/README.md
      - Payroll: modules/payroll/README.md
      - Tax Management: modules/tax/README.md
    - Customer Experience:
      - Customers: modules/customers/README.md
      - Loyalty: modules/loyalty/README.md
      - Feedback: modules/feedback/README.md
      - Promotions: modules/promotions/README.md
      
  - Architecture:
    - architecture/README.md
    - System Design:
      - Microservices: architecture/microservices.md
      - Database Design: architecture/database.md
      - Event System: architecture/events.md
    - Security:
      - Authentication: architecture/auth.md
      - Authorization: architecture/rbac.md
      - Data Protection: architecture/security.md
    - Performance:
      - Caching Strategy: architecture/caching.md
      - Scaling: architecture/scaling.md
      
  - API Reference:
    - api/README.md
    - Core APIs:
      - Authentication: api/auth.md
      - Orders: api/orders.md
      - Menu: api/menu.md
      - Staff: api/staff.md
    - Integration APIs:
      - Webhooks: api/webhooks.md
      - POS Sync: api/pos-sync.md
    - Tools:
      - SDKs: api/sdks.md
      - Postman Collection: api/postman.md
      
  - Deployment:
    - deployment/README.md
    - Production Setup:
      - Docker Deployment: deployment/docker.md
      - Kubernetes: deployment/kubernetes.md
      - Cloud Platforms: deployment/cloud.md
    - Operations:
      - Monitoring: deployment/monitoring.md
      - Backup & Recovery: deployment/backup.md
      - Scaling: deployment/scaling.md
      
  - Developer Guide:
    - Development:
      - Setup: guides/development-workflow.md
      - Testing: guides/testing.md
      - Code Style: guides/code-style.md
    - Advanced Topics:
      - Menu Versioning: guides/features/menu-versioning-architecture.md
      - Multi-Location: guides/features/multi-location.md
      - Custom Integrations: guides/custom-integrations.md
      
  - Resources:
    - Support:
      - FAQ: guides/faq.md
      - Troubleshooting: guides/troubleshooting.md
      - Contact: support.md
    - Reference:
      - Glossary: glossary.md
      - Error Codes: reference/errors.md
      - API Limits: reference/limits.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - fenced_code
  - codehilite:
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]'
      min_search_length: 3
      prebuild_index: true
      indexing: 'full'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - mike:  # For versioning
      canonical_version: latest
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
  version:
    provider: mike
    default: latest
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AuraTechWave
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/auraconnect
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/auratechwave
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: false  # Remove "Made with Material for MkDocs" footer

copyright: |
  &copy; 2025 <a href="https://auratechwave.com" target="_blank" rel="noopener">AuraTechWave</a>
