apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: auraconnect
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: auraconnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: auraconnect/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: auraconnect-config
              key: REACT_APP_API_URL
        - name: REACT_APP_WEBSOCKET_URL
          valueFrom:
            configMapKeyRef:
              name: auraconnect-config
              key: REACT_APP_WEBSOCKET_URL
        - name: REACT_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: auraconnect-config
              key: REACT_APP_ENVIRONMENT
        - name: REACT_APP_GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: auraconnect-secrets
              key: REACT_APP_GOOGLE_MAPS_API_KEY
        - name: REACT_APP_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: auraconnect-secrets
              key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        - name: REACT_APP_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: auraconnect-secrets
              key: REACT_APP_SENTRY_DSN
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: auraconnect
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80