name: CI Backend Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r backend/requirements.txt

      - name: Run flake8 on backend
        run: flake8 backend

      - name: Test Python imports
        run: |
          cd backend
          python -c "import sys; sys.path.append('.'); from app.main import app; print('✅ Backend imports successful')"
        
      - name: Check Alembic configuration
        run: |
          cd backend
          python -c "
          import sys
          sys.path.append('.')
          sys.path.append('../')
          try:
              from alembic.config import Config
              from alembic import command
              print('✅ Alembic configuration valid')
          except Exception as e:
              print(f'❌ Alembic configuration error: {e}')
              sys.exit(1)
          "
