name: Documentation Check

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - '.github/workflows/docs-check.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for mike versioning
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mike  # For versioning
    
    - name: Build documentation (strict mode)
      run: |
        mkdocs build --strict --verbose
    
    - name: Check for broken links
      run: |
        pip install linkchecker
        linkchecker --config .linkcheckerrc site/ || true
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: docs-build-logs
        path: |
          site/
          *.log

  validate-mermaid:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install mermaid-cli
      run: npm install -g @mermaid-js/mermaid-cli
    
    - name: Validate Mermaid diagrams
      run: |
        find docs -name "*.md" -exec grep -l "```mermaid" {} \; | while read file; do
          echo "Checking $file"
          # Extract and validate mermaid diagrams
          awk '/```mermaid/,/```/' "$file" | sed '1d;$d' > temp.mmd
          if [ -s temp.mmd ]; then
            mmdc -i temp.mmd -o output.png || echo "Error in $file"
          fi
        done
        rm -f temp.mmd output.png

  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --no-progress './docs/**/*.md' --exclude-mail
        fail: false  # Don't fail on external links

  spell-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Spell Check
      uses: streetsidesoftware/cspell-action@v2
      with:
        files: 'docs/**/*.md'
        config: '.cspell.json'
        strict: false